//Successful Status Codes
const OK_CODE = 200;
const OK_MESSAGE = 'OKAY.';

const CREATED_CODE = 201;
const CREATED_MESSAGE = 'Resource Created.';

const ACCEPTED_CODE = 202;
const ACCEPTED_MESSAGE = 'Request not completed.';

const THIRD_PARTY_CODE = 203;
const THIRD_PARTY_MESSAGE = 'Third party data.';

const NO_CONTENT_CODE = 204;
const NO_CONTENT_MESSAGE = 'No body content.';

const RESET_CODE = 205;
const RESET_MESSAGE = 'Reset data.';

const PARTIAL_CODE = 206;
const PARTIA_MESSAGE = 'Partial Data returned.';

//Redirection Status Codes
const LINK_CODE = 300;
const LINK_MESSAGE = 'Third party resource link.';

const RESOURCE_MOVED_CODE = 301;
const RESOURCE_MOVED_MESSAGE = 'Resource is moved permanetly.';

const RESOURCE_FOUND_CODE = 302;
const RESOURCE_FOUND_MESSAGE = 'Resource is moved to temporary url.';

const RESOURCE_FOUND2_CODE = 303;
const RESOURCE_FOUND2_MESSAGE = 'Resource is found in another url.';

const PROXY_CODE = 305;
const PROXY_MESSAGE = 'Resource must be accessed through the proxy.';

const UNUSED_CODE = 306;
const UNUSED_MESSAGE = 'The code is no longer available in this new version.';

//Client Error Code
const BAD_REQUEST_CODE = 400;
const BAD_REQUEST_MESSAGE = 'The server did not understand the request.';

const UNAUTHORIZED_CODE = 401;
const UNAUTHORIZED_MESSAGE = 'Unathorized Access.';

const PAYMENT_REQUIRED_CODE = 402;
const PAYMENT_REQUIRED_MESSAGE = 'You need to get paid version.';

const FORBIDDEN_CODE = 403;
const FORBIDDEN_MESSAGE = 'The request is forbidden.';

const NOT_FOUND_CODE = 404;
const NOT_FOUND_MESSAGE = 'The request is not found.';

const NOT_ACCEPTABLE_CODE = 406;
const NOT_ACCEPTABLE_MESSAGE = 'The request can only generate response that is not acceptable by client.';

const PROXY_AUTHENTICATION_REQUIRED_CODE = 407;
const PROXY_AUTHENTICATION_REQUIRED_MESSAGE = 'Proxy authntication is required.';

const REQUEST_TIMEOUT_CODE = 408;
const REQUEST_TIMEOUT_MESSAGE = 'Request timeout.';

const RESOURCE_UNAVAILABLE_CODE = 410;
const RESOURCE_UNAVAILABLE_MESSAGE = 'Resource is unavailable.';

const RESOURCE_TOO_LARGE_CODE = 413;
const RESOURCE_TOO_LARGE_MESSAGE = 'Resource is too large.';

//Server Error Code
const INTERNAL_SERVER_ERROR_CODE = 500;
const INTERNAL_SERVER_ERROR_MESSAGE = 'Oops! Something unexpected happened. Please try again.';

const BAD_GATEWAY_CODE = 502;
const BAD_GATEWAY_MESSAGE = 'Bad gateway. Thire party did not responed well.';

const SERVICE_UNAVAILABLE_CODE = 503;
const SERVICE_UNAVAILABLE_MESSAGE = 'Server overloaded.';

const GATEWAY_TIMEOUT_CODE = 504;
const GATEWAY_TIMEOUT_MESSAGE = 'The gateway is timed out.';

const HTTP_UNSUPPORTED_CODE = 505;
const HTTP_UNSUPPORTED_MESSAGE = 'The server does not support HTTP protocol.';

module.exports = Object.freeze({
    'OK_CODE' : OK_CODE,
    'OK_MESSAGE' : OK_MESSAGE,
    'CREATED_CODE' : CREATED_CODE,
    'CREATED_MESSAGE' : CREATED_MESSAGE,
    'ACCEPTED_CODE' : ACCEPTED_CODE,
    'ACCEPTED_MESSAGE' : ACCEPTED_MESSAGE,
    'THIRD_PARTY_CODE' : THIRD_PARTY_CODE,
    'THIRD_PARTY_MESSAGE' : THIRD_PARTY_MESSAGE,
    'NO_CONTENT_CODE' : NO_CONTENT_CODE,
    'NO_CONTENT_MESSAGE' : NO_CONTENT_MESSAGE,
    'RESET_CODE' : RESET_CODE,
    'RESET_MESSAGE' : RESET_MESSAGE,
    'PARTIAL_CODE' : PARTIAL_CODE,
    'PARTIA_MESSAGE' : PARTIA_MESSAGE,
    'LINK_CODE' : LINK_CODE,
    'LINK_MESSAGE' : LINK_MESSAGE,
    'RESOURCE_MOVED_CODE' : RESOURCE_MOVED_CODE,
    'RESOURCE_MOVED_MESSAGE' : RESOURCE_FOUND_MESSAGE,
    'RESOURCE_FOUND_CODE' : RESOURCE_FOUND_CODE,
    'RESOURCE_FOUND_MESSAGE' : RESOURCE_FOUND_MESSAGE,
    'RESOURCE_FOUND2_CODE' : RESOURCE_FOUND2_CODE,
    'RESOURCE_FOUND2_MESSAGE' : RESOURCE_FOUND2_MESSAGE,
    'PROXY_CODE' : PROXY_CODE,
    'PROXY_MESSAGE' : PROXY_MESSAGE,
    'UNUSED_CODE' : UNUSED_CODE,
    'UNUSED_MESSAGE' : UNUSED_MESSAGE,
    'BAD_REQUEST_CODE' : BAD_REQUEST_CODE,
    'BAD_REQUEST_MESSAGE' : BAD_REQUEST_MESSAGE,
    'UNAUTHORIZED_CODE' : UNAUTHORIZED_CODE,
    'UNAUTHORIZED_MESSAGE' : UNAUTHORIZED_MESSAGE,
    'PAYMENT_REQUIRED_CODE' : PAYMENT_REQUIRED_CODE,
    'PAYMENT_REQUIRED_MESSAGE' : PAYMENT_REQUIRED_MESSAGE,
    'FORBIDDEN_CODE' : FORBIDDEN_CODE,
    'FORBIDDEN_MESSAGE' : FORBIDDEN_MESSAGE,
    'NOT_FOUND_CODE' : NOT_FOUND_CODE,
    'NOT_FOUND_MESSAGE' : NOT_FOUND_MESSAGE,
    'NOT_ACCEPTABLE_CODE' : NOT_ACCEPTABLE_CODE,
    'NOT_ACCEPTABLE_MESSAGE' : NOT_ACCEPTABLE_MESSAGE,
    'PROXY_AUTHENTICATION_REQUIRED_CODE' : PROXY_AUTHENTICATION_REQUIRED_CODE,
    'PROXY_AUTHENTICATION_REQUIRED_MESSAGE' : PROXY_AUTHENTICATION_REQUIRED_MESSAGE,
    'REQUEST_TIMEOUT_CODE' : REQUEST_TIMEOUT_CODE,
    'REQUEST_TIMEOUT_MESSAGE' : REQUEST_TIMEOUT_MESSAGE,
    'RESOURCE_UNAVAILABLE_CODE' : RESOURCE_UNAVAILABLE_CODE,
    'RESOURCE_UNAVAILABLE_MESSAGE' : RESOURCE_UNAVAILABLE_MESSAGE,
    'RESOURCE_TOO_LARGE_CODE' : RESOURCE_TOO_LARGE_CODE,
    'RESOURCE_TOO_LARGE_MESSAGE' : RESOURCE_TOO_LARGE_MESSAGE,
    'INTERNAL_SERVER_ERROR_CODE' : INTERNAL_SERVER_ERROR_CODE,
    'INTERNAL_SERVER_ERROR_MESSAGE' : INTERNAL_SERVER_ERROR_MESSAGE,
    'BAD_GATEWAY_CODE' : BAD_GATEWAY_CODE,
    'BAD_GATEWAY_MESSAGE' : BAD_GATEWAY_MESSAGE,
    'SERVICE_UNAVAILABLE_CODE' : SERVICE_UNAVAILABLE_CODE,
    'SERVICE_UNAVAILABLE_MESSAGE' : SERVICE_UNAVAILABLE_MESSAGE,
    'GATEWAY_TIMEOUT_CODE' : GATEWAY_TIMEOUT_CODE,
    'GATEWAY_TIMEOUT_MESSAGE' : GATEWAY_TIMEOUT_MESSAGE,
    'HTTP_UNSUPPORTED_CODE' : HTTP_UNSUPPORTED_CODE,
    'HTTP_UNSUPPORTED_MESSAGE' : HTTP_UNSUPPORTED_MESSAGE
})
